### ISSUE TITLE
希望大佬制作一个完美卸载office for Mac的程序

### ISSUE THREAD

**Issue by caixiaohaier** [changanmoon/UninstallMAU#2]
发现大佬制作的这个卸载MAU程序非常好用，一键解决了问题。本人在重装office遇到很伤脑筋的问题，根据Google和MS官方提供的指南进行手动挨个删除文件，但好像都无法彻底删除，希望大佬能够制作一个能一键彻底删除office的程序，不胜感激。

**Comment by changanmoon** [comment]
怎么说呢……如果想达到这个需求，咱恐怕要另开一个 repo
因为开发 UninstallMAU 目的是为了卸载 Microsoft AutoUpdate，而不是卸载整个 Office，如果在此 repo 上继续更新，就要背离原来的意义了

此外补充：
1. Office for Mac 不只有 Office 2021 这个版本，还有以往的 Office 2019 和 Office 2016（更旧的还有 Office 2011，但这里不考虑，因为本来也是过时的软件），哪怕 Office 完整的组件，也不是 Word + Excel + PowerPoint 的简单组合
对于本项目 UninstallMAU 而言，Microsoft AutoUpdate 在 2016 至 2021 这几个版本间基本没什么变化，所以通用性很强，那么，推及到 Office 的卸载更应当如此
如果为了保证它的通用性，咱恐怕不能只关心最新的 Office，而是将三个版本和其组件的差异都得顾及到
2. 直到现在为止，使用 Big Sur 以下版本的 macOS 用户仍有一定的数目，然而咱手头的条件有限，不仅没有 Intel 机型的 Mac，而且在用的 Apple 芯片的 Mac 能通过虚拟化使用的 macOS 版本只有 Monterey 及以上，所以如果在旧版本 macOS 下测试的话还有不小的挑战，更不用说卸载还要达到“完美”的程度，即完全没有残留

所以基于上面这两点，咱可能需要对此多考虑一下，望您谅解……
感谢建议！(｀・ω・´)
