### ISSUE TITLE
update

### ISSUE THREAD

**Issue by jsda** [changanmoon/UninstallMAU#3]
sudo rm -rf /Library/LaunchAgents/com.microsoft.OneDriveStandaloneUpdater.plist

sudo rm -rf /Library/LaunchDaemons/com.microsoft.OneDriveStandaloneUpdaterDaemon.plist
sudo rm -rf /Library/LaunchDaemons/com.microsoft.OneDriveUpdaterDaemon.plist

**Comment by changanmoon** [comment]
Thanks for your comment! These changes have applied in version 1.2.
